apiVersion: v1
kind: Service
metadata:
  name: hello-service
spec:
  selector:
    app: hello-microservice
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer  # For Minikube use "NodePort"
